#!/bin/env python

#PBS -l nodes=1:ppn=1
#PBS -l vmem=1gb
#PBS -l walltime=00:05:00
#PBS -N stage
#PBS -q normal
#PBS -A TG-DBS170009

import json
import subprocess
import errno
import os
import sys

with open("config.json") as config_json:
    config = json.load(config_json)
    for dataset in config["datasets"]:

        storage = "wrangler"
        if "storage" in dataset:
            storage = dataset["storage"]

        outdir=dataset["id"]
        if 'outdir' in dataset:
            outdir=dataset["outdir"]

        if storage == "wrangler":
            try: 
                os.makedirs(outdir)
            except OSError as exc:
                if exc.errno == errno.EEXIST and os.path.isdir(outdir):
                    pass
                else:
                    raise

            src=os.environ["BRAINLIFE_ARCHIVE"]+"/"+dataset["project"]+"/"+dataset["id"]+".tar"
            code=subprocess.call(["tar", "xf", src, "-C", outdir])
            sys.exit(code)

        else:
            #download from brainlife download server
            print(["bl", "dataset", "download", dataset["id"], outdir])
            code=subprocess.call(["bl", "dataset", "download", dataset["id"], outdir])
            sys.exit(code)
            
