#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=1gb
#PBS -l walltime=00:05:00
#PBS -N stage

set -ex

#send all env with BRAINLIFE_ prefix to singularity
for e in $(env); do
  if [[ $e == BRAINLIFE_* ]]; then
    export SINGULARITYENV_$e
  fi
done

echo "making sure sif image is cached"
singularity exec -e docker://brainlife/stage whoami

echo "staging.."
#timeout 240 singularity exec -e docker://brainlife/datalad:0.14.3 ./main.py
timeout 240 singularity exec -e docker://brainlife/stage ./main.py

echo "converting data (for xnat)"
#timeout 180 singularity exec -e docker://brainlife/ezbids-handler:3.3 ./convert.py
timeout 180 singularity exec -e docker://brainlife/stage ./convert.py

echo "all done"
